use_frameworks!

platform :ios, '10.0'

target 'WeProovSDK_Example' do
	pod 'WeProovSDK', :path => '../'
    # pod 'WeProovSDK', :git => "https://github.com/ProovGroup/weproov-ios-sdk"
    
	target 'WeProovSDK_Tests' do
		inherit! :search_paths
	end
end
