use_frameworks!

platform :ios, '10.0'

target 'WeProovSDK_Example' do
	pod 'WeProovSDK', :path => '../'
	pod 'WeProovWprv', :git => 'git@github.com:ProovGroup/weproov-ios-wprv.git'

	target 'WeProovSDK_Tests' do
		inherit! :search_paths
	end
end
