language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="Example/WeProovSDK.xcworkspace"
  - SCHEME="WeProovSDK-Example"
  matrix:
    - DESTINATION="OS=12.0,name=iPhone XS"
    - DESTINATION="OS=11.4,name=iPhone X"
    - DESTINATION="OS=10.3.1,name=iPhone 7"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild ONLY_ACTIVE_ARCH=NO ARCHS="x86_64 arm64" -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug build | xcpretty
  - xcodebuild ONLY_ACTIVE_ARCH=NO ARCHS="x86_64 arm64" -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release build | xcpretty
